---
name: Scott Isaac Large
position: "Chief, Ecosystem Dynamics and Assessment Branch"
address: "NOAA-Fisheries, 166 Water Street, Woods Hole, Massachusetts, 02543"
phone: +1 (508)495-2346
email: "scott.large@noaa.gov"
twitter: ScottLarge_
github: slarge
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
output: vitae::awesomecv
header_includes:
  - \ExecuteBibliographyOptions{useprefix=true}
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
library(rorcid)
library(RefManageR)
source("https://raw.githubusercontent.com/robjhyndman/CV/master/Rpackages.R")
source("https://raw.githubusercontent.com/robjhyndman/CV/master/baretable.R")
knitr::opts_chunk$set(echo = FALSE)
```

```{r packages, include=FALSE}
write_packages_bib(
 pkglist = c("fedregs"),
 file="Rpackages.bib")
```

# Education
```{r}

## To do this part, you need to 

## 1) OAth orcid:
## rorcid::orcid_auth() # and copy the value after "Bearer"
## 2) set the .Renviron with that value
## usethis::edit_r_environ("project") # paste and save as ORCID_AUTH

orcid_ed <- rorcid::orcid_educations("0000-0001-7199-9972")$`0000-0001-7199-9972`

orcid_ed$`education-summary` %>%
  detailed_entries(
    what = `role-title`,
    when = glue::glue("{`start-date.year.value`} - {`end-date.year.value`}"),
    with = organization.name,
    where = glue::glue("{organization.address.city}, {organization.address.region}")
  )

```


# Employment history
```{r}

## To do this part, you need to 

## 1) OAth orcid:
## rorcid::orcid_auth() # and copy the value after "Bearer"
## 2) set the .Renviron with that value
## usethis::edit_r_environ("project") # paste and save as ORCID_AUTH

orcid_work <- rorcid::orcid_employments("0000-0001-7199-9972")$`0000-0001-7199-9972`

orcid_work$`employment-summary` %>%
  detailed_entries(
    what = dplyr::case_when(!is.na(`department-name`) ~ glue::glue("{`role-title`}–{`department-name`}"),
                            TRUE ~ `role-title`),
    when = dplyr::case_when(!is.na(`end-date.year.value`) ~ glue::glue("{`start-date.year.value`} - {`end-date.year.value`}"),
                            TRUE ~ glue::glue("{`start-date.year.value`} - present")),
    with = organization.name,
    where = dplyr::case_when(`organization.address.country` == "US" ~ glue::glue("{organization.address.city}, {organization.address.region}"),
                             `organization.address.country` == "DK" ~ glue::glue("{organization.address.city}, Denmark"))
  )

```

## Other positions

```{r positions, results='asis'}
tribble(
  ~Start, ~End, ~Position,
  2019, NA, "\\textbf{Associate Editor}, \\textit{Frontiers in Marine Science}"
) %>%
  mutate(End = replace_na(End, "present")) %>%
  mutate(Year = paste(Start, "–", End, sep = "")) %>%
  select(Year, Position) %>%
  baretable()
```


# Publications

## PhD thesis
```{r thesis}
bibliography_entries("large_pubs.bib", startlabel = "papersstart") %>%
  filter(bibtype == "PhdThesis")
```

## Refereed research papers
```{r research-papers}
 bibliography_entries("large_pubs.bib") %>%
   dplyr::filter(bibtype == "Article") %>%
   dplyr::arrange(year, author)

```

## Software (R packages)
```{r r-packages}
# Sort R packages by title, then year.
bibliography_entries("Rpackages.bib",
  startlabel = "packagestart", endlabel = "packageend"
) %>%
  arrange(title, year)
```

